### ISSUE TITLE
Parameters `connected_to` and `in_gazebo` of panda_arm.xacro

### ISSUE THREAD

**Issue by tgaspar** [justagist/franka_panda_description#3]
Hello there,

I was playing around the `panda_arm.xacro` file and noticed some odd behavior when assigning the `connected_to` and `in_gazebo` parameters. As it now stands, you cannot connect the `link0` to a different frame than `world` if you use gazebo (`in_gazebo=true`).

The conditional in [line 4](https://github.com/justagist/franka_panda_description/blob/8de1de945104cca8e82f1a30b9838e52d009f34e/robots/panda_arm.xacro#L4) will be overwritten by the conditional of [line 13](https://github.com/justagist/franka_panda_description/blob/8de1de945104cca8e82f1a30b9838e52d009f34e/robots/panda_arm.xacro#L13). 

Also, I don't really understand why are the inertial parameters of the `link0` assigned only when `is_gazebo` is true ([line 36](https://github.com/justagist/franka_panda_description/blob/8de1de945104cca8e82f1a30b9838e52d009f34e/robots/panda_arm.xacro#L36))

I noticed this when trying to mount the simulated robot on top of another frame, i.e. a table. Is this expected behavior and I just missed something obvious?

**Comment by justagist** [comment]
Thanks for pointing out the bug in `connected_to`. This should be fixed now.
The inertial parameters of link0 do not affect the dynamics or control behaviour of the robot and are therefore not really meaningful, but gazebo requires these to be defined anyway.

**Comment by tgaspar** [comment]
Thanks for the quick reply and commit. However, I do still have some issues with how this is implemented.

The way this work does not allow me to simply connect the robot to an existing frame. As soon as soon as I set `in_gazebo=true` and set `connected_to=my_frame` I get the error that `link 'world' is not unique`. Perhaps I would suggest a different implementation: 

```xml
...
    <xacro:property name="joint_damping" value="1.0"/>

    <xacro:unless value="${connected_to == ''}">
      <joint name="${arm_id}_joint_${connected_to}" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${arm_id}_link0"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
        <xacro:if value="${in_gazebo}">
          <dynamics damping="${joint_damping}"/>
        </xacro:if>
      </joint>
    </xacro:unless>
    <xacro:if value="${connected_to == ''}">
      <link name="world" />

      <joint name="robot_to_world" type="fixed">
        <parent link="world" />
        <child link="${arm_id}_link0" />
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        <xacro:if value="${in_gazebo}">
          <dynamics damping="${joint_damping}"/>
        </xacro:if>
      </joint>
    </xacro:if>
...
```
What do you think?

**Comment by justagist** [comment]
I understand what you mean, but your suggested fix would assume that a fixed frame and link 'world' is already defined in the tree in which the `$connected_to` frame exists.

**Comment by tgaspar** [comment]
Yes. I think that is a fair assumption. I believe that if someone want's to connect the robot to an already existing frame they take care that the `world` frame exist. 

Otherwise I don't fully understand under which condition would the frame `$connected_to` be used. 

These are just my thoughts. Perhaps I am wrong here but I did stumble on this being a problem when I wanted to mount the robot to an existing frame that was fully defined. Again, maybe I am using it wrong :)

**Comment by justagist** [comment]
You are right. I have now made that change. Thanks!

**Comment by tgaspar** [comment]
Thank you for developing this! I will be using your code stack in one of my projects and it's good to know that I can turn to you with questions.

I have no additional comments regarding this issue so feel free to close it.
